### PR TITLE
Add support for higher quality filtering

### LINKED ISSUE #275: Allow higher quality filtering
We've seen that a very common use case for layers is the display of documents or UI with text.
Currently, layers are tuned for performance but they have the ability to turn on extra filtering which improves text readability. See https://www.facebook.com/RealityLabs/videos/1021802275341764/ around the 14 minute mark.

Should we make this available for WebXR Layers? I envision that this could be an optional feature that UAs can ignore.

/agenda should we allow higher quality filtering?

### PR DESCRIPTION
**Pull request by cabanier**
Closes #275

***
<a href="https://pr-preview.s3.amazonaws.com/cabanier/layers/pull/302.html" title="Last updated on Apr 6, 2023, 5:22 PM UTC (b79f6a1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/layers/302/74a5958...cabanier:b79f6a1.html" title="Last updated on Apr 6, 2023, 5:22 PM UTC (b79f6a1)">Diff</a>

### CODE REVIEW

**Comment by cabanier** [comment]
/agenda discuss new filtering enum in WebXR Layers

**Comment by AdaRoseCannon** [comment]
I like that the purpose of the different optimised modes are stated. Perhaps the default should say performance optimised, or what it's intended purpose should be?

**Comment by cabanier** [comment]
> I like that the purpose of the different optimised modes are stated. Perhaps the default should say performance optimised, or what it's intended purpose should be?

performance optimized is a good option!

**Comment by toji** [comment]
Agreed with Ada that "performance" is a better option, but I'm mildly worried that it makes it sound like a higher performance option than "default", and don't want developers flipping that bit if their aim is to get the fastest performance.

Maybe the progression could be like:

"high-performance" -> "image-quality" -> "text-quality"

**Comment by cabanier** [comment]
> Agreed with Ada that "performance" is a better option, but I'm mildly worried that it makes it sound like a higher performance option than "default", and don't want developers flipping that bit if their aim is to get the fastest performance.
> 
> Maybe the progression could be like:
> 
> "high-performance" -> "image-quality" -> "text-quality"

except for Quest, image quality is more expensive than text quality. 
I prefer to keep "default" as it doesn't make any promises.

**Comment by cabanier** [comment]
@toji thoughts on this?

**Comment by AdaRoseCannon** [comment]
I think ‘system’ or ‘standard’ work well to describe ’you get what you get, don’t do anything special’

**Comment by cabanier** [comment]
> I think ‘system’ or ‘standard’ work well to describe ’you get what you get, don’t do anything special’

Wouldn't `default` imply that as well?
I searched all the IDL files and `default` is used many times in web APIs (ie [this file](https://github.com/chromium/chromium/blob/main/third_party/blink/renderer/core/imagebitmap/image_bitmap_options.idl)).

**Comment by AdaRoseCannon** [comment]
That's fine, as I mentioned in the meeting, I am persuaded on default and it isn't a hill I'll die on

**Comment by cabanier** [comment]
> That's fine, as I mentioned in the meeting, I am persuaded on default and it isn't a hill I'll die on

Do you or @toji want to sign off on this then? :-)

**Review by Manishearth — APPROVED** [review]

**Pull request merged**
