### PR TITLE
Added support for scalefactor

### PR DESCRIPTION
**Pull request by cabanier**

### CODE REVIEW

**Comment by cabanier** [comment]
hmm, I have the green "Confirm merge" button. Will we lose something if I press it?

**Comment by toji** [comment]
Huh... that's interesting. I'd say give it a go! We can look at the commit history to see if it does anything we didn't want.

**Comment by toji** [comment]
I don't see anything unexpected being removed/changed in the [merge commit](https://github.com/immersive-web/layers/commit/a5cae6e221f3e3dc43c6786a83438ecbeaa125a4), so I think we're good!

**Comment by cabanier** [comment]
and the spec was rebuilt as well.
Thanks for setting that up!

**Pull request merged**
