### PR TITLE
changed hardcoded number to number of views

### LINKED ISSUE #114: How should layers behave when there's more than two views of the scene?
For example, devices may have a third view for an on-board camera, used when generating screen recordings (so the XR content lines up with the real-world content).

### PR DESCRIPTION
**Pull request by cabanier**
fixes #114

### CODE REVIEW

**Comment by cabanier** [comment]
> There are a couple of uses of the word "double" left at https://github.com/cabanier/layers/blob/textureperview/webxrlayers-1.bs#L669-L670 which should become "numViews times". Apart from that, LGTM, thanks!

Those need to stay. Those layouts are designed for stereo artwork (such as video) and it will be unexpected that they suddenly need an extra view.

**Comment by asajeffrey** [comment]
> > There are a couple of uses of the word "double" left at https://github.com/cabanier/layers/blob/textureperview/webxrlayers-1.bs#L669-L670 which should become "numViews times". Apart from that, LGTM, thanks!
> 
> Those need to stay. Those layouts are designed for stereo artwork (such as video) and it will be unexpected that they suddenly need an extra view.

Hmm, in that case should `stereo-left-right` and `stereo-top-bottom` throw an exception if there's anything other than two views?

**Comment by cabanier** [comment]
> > Those need to stay. Those layouts are designed for stereo artwork (such as video) and it will be unexpected that they suddenly need an extra view.
> 
> Hmm, in that case should `stereo-left-right` and `stereo-top-bottom` throw an exception if there's anything other than two views?

Would having more than 2 views be feature that the author is opting in?
If so, maybe it's ok to have more than 2 views for a side-by-side texture.

**Comment by asajeffrey** [comment]
Hmm, interesting question about how the number of views would be negotiated. It would be nice if there common case was that content would work on all devices, but there are odd cases like spectator view, where it's not obvious how something like stereo video should be composited if there's a spectator view.

**Comment by cabanier** [comment]
> Hmm, interesting question about how the number of views would be negotiated. It would be nice if there common case was that content would work on all devices, but there are odd cases like spectator view, where it's not obvious how something like stereo video should be composited if there's a spectator view.

Yes, we probably would display the left or right video.
Let's merge the PR for now and see if we can merge a new view name (`camera`?) into WebXR and then we can special case it in the layers spec.

**Comment by asajeffrey** [comment]
Sound good, thanks for making the changes!

**Pull request merged**
