### PR TITLE
Fix up the pending layers state

### PR DESCRIPTION
**Pull request by cabanier**
Remove the reliance on 'layers' feature

***
<a href="https://pr-preview.s3.amazonaws.com/cabanier/layers/pull/194.html" title="Last updated on Aug 6, 2020, 7:11 PM UTC (bf0fc2d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/layers/194/fa3a435...cabanier:bf0fc2d.html" title="Last updated on Aug 6, 2020, 7:11 PM UTC (bf0fc2d)">Diff</a>

### CODE REVIEW

**Comment by cabanier** [comment]
Closes #193

**Comment by toji** [comment]
LGTM, but I wonder if a check for the "layers" feature ought to be added back in for array lengths > 1?

**Comment by asajeffrey** [comment]
@toji if it makes any difference, Servo will soon support multiple projection and `XRWebGLLayer`s, but not quad, cylinder etc.

**Comment by cabanier** [comment]
> LGTM, but I wonder if a check for the "layers" feature ought to be added back in for array lengths > 1?

Yes, right now we imply that any number of projection layers should be supported by default.
Should I open an issue?

**Comment by toji** [comment]
I thought that in a previous discussion on one of the calls we decided that the "layers" feature would limit both non-projection layers _and_ multi-layer. We can re-evaluate that if we want, especially if it looks like the multi-layer part of it will be easy to support across the board.

**Comment by cabanier** [comment]
> I thought that in a previous discussion on one of the calls we decided that the "layers" feature would limit both non-projection layers _and_ multi-layer. We can re-evaluate that if we want, especially if it looks like the multi-layer part of it will be easy to support across the board.

Yes, we discussed this before but I don't think this was decided.
Can you open an issue so we can discuss? This is likely not an issue for UA's that implement the full layers spec but it might be hard for others (like Magic Leap or cellphone AR)

**Pull request merged**
